"""updated foreign keys

Revision ID: 25eea51a3b65
Revises: 45ea4dea1242
Create Date: 2020-04-28 15:08:10.014169

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '25eea51a3b65'
down_revision = '45ea4dea1242'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lessons', 'group_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('lessons', 'subject_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('lessons', 'teacher_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lessons', 'teacher_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('lessons', 'subject_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('lessons', 'group_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###
