"""empty message

Revision ID: 3a7a66665b7a
Revises: 5251e342f317
Create Date: 2020-04-27 18:55:33.605710

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3a7a66665b7a'
down_revision = '5251e342f317'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_username'), 'admin', ['username'], unique=True)
    op.alter_column('groups', 'name',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_unicode_ci', length=45),
               nullable=True)
    op.drop_index('FK_GROUP_idx', table_name='lessons')
    op.drop_index('FK_SUBJECT_idx', table_name='lessons')
    op.drop_index('FK_TEACHER_idx', table_name='lessons')
    op.alter_column('subjects', 'subj_type',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=45),
               nullable=True)
    op.alter_column('subjects', 'title',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=255),
               nullable=True)
    op.alter_column('teachers', 'name',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=45),
               nullable=True)
    op.alter_column('teachers', 'patronymic',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=45),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teachers', 'patronymic',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=45),
               nullable=False)
    op.alter_column('teachers', 'name',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=45),
               nullable=False)
    op.alter_column('subjects', 'title',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=255),
               nullable=False)
    op.alter_column('subjects', 'subj_type',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=45),
               nullable=False)
    op.create_index('FK_TEACHER_idx', 'lessons', ['teacher_id'], unique=False)
    op.create_index('FK_SUBJECT_idx', 'lessons', ['subject_id'], unique=False)
    op.create_index('FK_GROUP_idx', 'lessons', ['group_id'], unique=False)
    op.alter_column('groups', 'name',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_unicode_ci', length=45),
               nullable=False)
    op.drop_index(op.f('ix_admin_username'), table_name='admin')
    op.drop_table('admin')
    # ### end Alembic commands ###
