"""empty message

Revision ID: 45ea4dea1242
Revises: 52806836a321
Create Date: 2020-04-28 12:51:44.228334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45ea4dea1242'
down_revision = '52806836a321'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('order', table_name='lessons')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('order', 'lessons', ['order'], unique=True)
    # ### end Alembic commands ###
