"""updated lesson table

Revision ID: 52806836a321
Revises: 4a7a6151f88e
Create Date: 2020-04-28 11:56:47.340901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52806836a321'
down_revision = '4a7a6151f88e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'lessons', ['order'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lessons', type_='unique')
    # ### end Alembic commands ###
