"""added tables

Revision ID: 68bacc05d799
Revises: 
Create Date: 2020-04-26 12:09:22.994455

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '68bacc05d799'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('groups', 'name',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=45),
               nullable=True)
    op.alter_column('lessons', 'auditory',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=45),
               nullable=True)
    op.alter_column('lessons', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('lessons', 'group_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('lessons', 'order',
               existing_type=mysql.TINYINT(display_width=4),
               nullable=True)
    op.alter_column('lessons', 'subject_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('lessons', 'teacher_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_index('FK_GROUP_idx', table_name='lessons')
    op.drop_index('FK_SUBJECT_idx', table_name='lessons')
    op.drop_index('FK_TEACHER_idx', table_name='lessons')
    op.add_column('subjects', sa.Column('subj_type', sa.String(length=45), nullable=True))
    op.alter_column('subjects', 'title',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=255),
               nullable=True)
    op.drop_column('subjects', 'type')
    op.alter_column('teachers', 'name',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=45),
               nullable=True)
    op.alter_column('teachers', 'patronymic',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=45),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teachers', 'patronymic',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=45),
               nullable=False)
    op.alter_column('teachers', 'name',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=45),
               nullable=False)
    op.add_column('subjects', sa.Column('type', mysql.VARCHAR(collation='utf8_unicode_ci', length=45), nullable=False))
    op.alter_column('subjects', 'title',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=255),
               nullable=False)
    op.drop_column('subjects', 'subj_type')
    op.create_index('FK_TEACHER_idx', 'lessons', ['teacher_id'], unique=False)
    op.create_index('FK_SUBJECT_idx', 'lessons', ['subject_id'], unique=False)
    op.create_index('FK_GROUP_idx', 'lessons', ['group_id'], unique=False)
    op.alter_column('lessons', 'teacher_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('lessons', 'subject_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('lessons', 'order',
               existing_type=mysql.TINYINT(display_width=4),
               nullable=False)
    op.alter_column('lessons', 'group_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('lessons', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('lessons', 'auditory',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=45),
               nullable=False)
    op.alter_column('groups', 'name',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=45),
               nullable=False)
    # ### end Alembic commands ###
